// 10 ready-made Kaspa app UI templates. Each is a rich build prompt.
export const KASPA_TEMPLATES = [
  {
    id: "wallet",
    name: "Kaspa Wallet",
    tag: "Wallet",
    emoji: "👛",
    blurb: "Balance, send, receive, history",
    prompt: "Build a native Kaspa wallet app UI: big balance card in KAS with live USD value, Send / Receive / History tabs, address QR code, transaction list with confirmations and timestamps, and a seed-phrase backup flow. Dark theme, teal #70C7BA accents, glassy cards, mobile-first.",
  },
  {
    id: "explorer",
    name: "BlockDAG Explorer",
    tag: "Explorer",
    emoji: "🔍",
    blurb: "Live blocks, tx search, address pages",
    prompt: "Build a Kaspa BlockDAG explorer UI: search bar for tx/address/block, live streaming block feed with BPS counter, animated DAG visualisation, network stats (hashrate, difficulty, circulating supply), and detail panels for transactions and addresses. Dark, data-dense, monospace numbers, teal accents.",
  },
  {
    id: "dashboard",
    name: "Price Dashboard",
    tag: "Markets",
    emoji: "📈",
    blurb: "Live KAS price, charts, alerts",
    prompt: "Build a Kaspa market dashboard: live KAS price header with 24h change, candlestick chart with timeframe switcher, market cap / volume / supply stat cards, top exchanges table, and a price-alert panel. Dark trading-terminal look with teal and red/green candles.",
  },
  {
    id: "mining",
    name: "Mining Pool",
    tag: "Mining",
    emoji: "⛏️",
    blurb: "Hashrate, workers, payouts",
    prompt: "Build a Kaspa mining pool dashboard: pool hashrate hero with sparkline, miner search by address, worker table with hashrate/shares/status, earnings and payout history, and a getting-started connect guide with copyable stratum config. Industrial dark UI, teal accents.",
  },
  {
    id: "krc20",
    name: "KRC-20 Token Hub",
    tag: "Tokens",
    emoji: "🪙",
    blurb: "Token list, mint, deploy",
    prompt: "Build a KRC-20 token hub for Kaspa: searchable token grid with logos, supply and holder counts, token detail page with mint progress bar and holder distribution chart, plus deploy and mint forms. Clean dark UI, teal highlights, card grid.",
  },
  {
    id: "dex",
    name: "Kaspa DEX",
    tag: "DeFi",
    emoji: "🔁",
    blurb: "Swap, pools, order book",
    prompt: "Build a Kaspa DEX trading UI: swap card with token selectors and slippage settings, order book with bids/asks, live trade history feed, price chart, and liquidity pool list with APR. Dark exchange aesthetic, teal primary, dense but readable.",
  },
  {
    id: "nft",
    name: "NFT Marketplace",
    tag: "NFT",
    emoji: "🖼️",
    blurb: "Collections, mint, gallery",
    prompt: "Build a Kaspa NFT marketplace UI: featured collection hero, filterable NFT grid with price in KAS, item detail modal with traits and offer history, and a mint page with quantity selector and live supply counter. Dark gallery look, teal accents, generous whitespace.",
  },
  {
    id: "payments",
    name: "Merchant Payments",
    tag: "Payments",
    emoji: "💳",
    blurb: "POS checkout with KAS",
    prompt: "Build a Kaspa merchant payment terminal UI: numeric keypad for amount entry, live KAS/USD conversion, generated payment QR with countdown timer, confirmation success animation, and a transaction log for the day with totals. Clean, high-contrast, touch-friendly POS design.",
  },
  {
    id: "staking",
    name: "Staking / Rewards",
    tag: "Rewards",
    emoji: "🏦",
    blurb: "Lock KAS, track rewards",
    prompt: "Build a Kaspa staking and rewards UI: total staked hero with APR, lock-amount form with duration slider, active positions list with unlock countdowns, rewards claim card, and a rewards-over-time chart. Dark, premium, teal-to-cyan gradients.",
  },
  {
    id: "community",
    name: "Community Hub",
    tag: "Social",
    emoji: "🌐",
    blurb: "News, feed, tipping",
    prompt: "Build a Kaspa community hub: news feed with article cards, community posts with reactions and KAS tipping buttons, ecosystem app directory grid, and an events calendar. Dark social layout with sidebar navigation and teal accents.",
  },
];